language: java
install:
  - sudo apt-get update
  - sudo apt-get install python3
  - sudo apt-get install python3-pip
  - sudo pip3 install -r requirements.txt
jobs:
  include:
    - stage: Build plugin resources
      script: python3 scripts/build.py
    - script: python3 scripts/changelog.py
    - script: python3 scripts/readme.py
    - stage: Build plugin
      script: ./gradlew build
    - stage: Test plugin
      script: python3 -m unittest discover
deploy:
  - provider: releases
    api_key: $GITHUB_AUTH_TOKEN
    file_glob: true
    file: build/libs/*.jar
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: ./gradlew publishPlugin
    skip_cleanup: true
    on:
      tags: true
env:
  - VERSION=${TRAVIS_TAG/v/}
notifications:
  email:
    recipients:
      - $ADMIN_EMAIL
    on_success: change
    on_failure: always
