name: Pre-Merge Actions

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for scripts
      run: chmod +x gradlew
    - run: ./ciScripts/buildPlugin.sh
      env:
        VERSION: 999
        RELEASE_NOTES: '-This is a test and should not be released.\n-Also a test there might be a character minimum'
    - uses: thepieterdc/intellij-plugin-verifier-action@v1.1.2
      with:
        plugin: '/home/runner/work/jetbrains-one-dark-theme/jetbrains-one-dark-theme/build/distributions/one-dark-theme*'
        versions: |
          2020.1.2
          LATEST-EAP-SNAPSHOT