name: Pre-Merge Actions

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for scripts
      run: chmod +x gradlew
#    - name: Perform quality check
#      run: ./gradlew clean check
    - run: ./ciScripts/buildPlugin.sh
      env:
        RELEASE_NOTES: ${{ github.event.release.body }}
        VERSION: ${{ github.ref }}
    - name: IntelliJ Plugin Verifier
      uses: thepieterdc/intellij-plugin-verifier-action@v1.1.2
      plugin: '/home/runner/work/jetbrains-one-dark-theme/jetbrains-one-dark-theme/build/distributions/one-dark-theme*'
#      todo: change to 2020 once ready
      versions: |
        2019.1.4
        2019.2.4
        2019.3.4